theme = "lynx"
title = "Kevin BRAULT - Computer engineer"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Hi! I'm Kévin"
  headline = "I'm a computer engineer from France 🥖"
  image = "author.jpg"
  links = [
    { github = "https://github.com/kbrault" },
    { medium = "https://kbrault.medium.com/" }
  ]
